<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Basket\Api\Representation\BasketItemRepresentation|null $basketItem
 * @var string $url
 * and options passed from the caller.
 */

$translate = $this->plugin('translate');

$textSelect[] = $translate('Add to basket');
$textSelect[] = $translate('Remove from basket');
if (empty($basketItem)):
    $class = 'unselected';
else:
    $textSelect = array_reverse($textSelect);
    $class = 'selected';
endif;
?>

<button class="basket-update <?= $class ?>" data-id="<?= $resource->id() ?>" title="<?= $textSelect[0] ?>" data-title-toggle="<?= $textSelect[1] ?>" data-url="<?= $url ?>">
</button>
