<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Selection\Api\Representation\SelectionItemRepresentation|null $selectionItem
 * @var string $url
 * and options passed from the caller.
 */

$translate = $this->plugin('translate');

$textSelect[] = $translate('Add to selection');
$textSelect[] = $translate('Remove from selection');
if (empty($selectionItem)):
    $class = 'unselected';
else:
    $textSelect = array_reverse($textSelect);
    $class = 'selected';
endif;
?>

<button class="selection-update <?= $class ?>" data-id="<?= $resource->id() ?>" title="<?= $textSelect[0] ?>" data-title-toggle="<?= $textSelect[1] ?>" data-url="<?= $url ?>">
</button>
