<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $values
 */

$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$ark = $this->getHelperPluginManager()->has('ark') ? $this->plugin('ark') : false;
?>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <h4>
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($propertyData['property']->label()); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
            <?php foreach ($propertyData['values'] as $value): ?>
                <?php
                $class = ['value'];
                if ('resource' == $value->type()) {
                    $class[] = 'resource';
                    $class[] = $escape($value->valueResource()->resourceName());
                } elseif ('uri' == $value->type()) {
                    $class[] = 'uri';
                }
                // For Omeka < 1.3.
                if (method_exists($value, 'isPublic') && !$value->isPublic()) {
                    $class[] = 'private';
                }
                ?>
                <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                    <?php if ($language = $value->lang()): ?>
                    <span class="language"><?php echo $language; ?></span>
                    <?php endif; ?>
                    <?php
                    if ($ark && $term === 'dcterms:identifier' && strpos($value, 'ark:/') === 0):
                        $ark = $this->getHelperPluginManager()->get('ark');
                        $url = method_exists($ark, 'getAbsoluteUrl')
                            ? $ark($value->resource())->getAbsoluteUrl() // Deprecated since 3.5.3 and removed in 3.5.7.
                            : $ark($value->resource())->url(['force_canonical' => true], false);
                        echo $this->hyperlink($value, $url);
                    else:
                        echo $value->asHtml();
                    endif;
                    ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
