<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$translate = $this->plugin('translate');

$this->headScript()->appendFile($this->assetUrl('js/custom.js'), 'text/javascript', ['defer' => 'defer']);

$hasBasket = $this->getHelperPluginManager()->has('updateBasketLink');
$ark = $this->getHelperPluginManager()->has('ark') ? $this->ark($resource)->url(['force_canonical' => true], false): null;
$isMedia = $resource->resourceName() === 'media';
?>

<div id="psl-toolbox">
    <ul>
        <?php if ($hasBasket): ?>
        <li class="basket"><?php echo $this->updateBasketLink($resource); ?></li>
        <?php endif; ?>
        <?php if ($ark): ?>
        <li class="share">
            <a href="#psl-toolbox-share"></a>
        </li>
        <?php endif; ?>
        <?php if ($isMedia): ?>
            <li class="download">
                <a href="#psl-toolbox-download"></a>
            </li>
        <?php endif; ?>
    </ul>
    <?php if ($ark): ?>
    <div id="psl-toolbox-share">
        <label><?php echo $translate('Permalink'); ?></label>
        <a href="<?php echo $ark; ?>"><?php echo $ark; ?></a>
    </div>
    <?php endif; ?>
    <?php if ($isMedia): ?>
        <div id="psl-toolbox-download">
            <label><?php echo $translate('Original file:'); ?></label>
            <a href="<?php echo $resource->originalUrl(); ?>"><?php echo $resource->filename(); ?></a>
        </div>
    <?php endif; ?>
</div>
