<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$this->headScript()->appendFile($this->assetUrl('js/custom.js'), 'text/javascript', ['defer' => 'defer']);

$hasSelection = $plugins->has('updateSelectionLink');
$hasBasket = !$hasSelection && $plugins->has('updateBasketLink');

if ($plugins->has('ark')):
    $ark = $plugins->get('ark');
    $ark = method_exists($ark, 'getAbsoluteUrl')
        ? $ark($resource)->getAbsoluteUrl() // Deprecated since 3.5.3 and removed in 3.5.7.
        : $ark($resource)->url(['force_canonical' => true], false);
else:
    $ark = null;
endif;

$isMedia = $resource->resourceName() === 'media';
?>

<div id="psl-toolbox">
    <ul>
        <?php if ($hasSelection): ?>
        <li class="selection"><?php echo $this->updateSelectionLink($resource); ?></li>
        <?php elseif ($hasBasket): ?>
        <li class="basket"><?php echo $this->updateBasketLink($resource); ?></li>
        <?php endif; ?>
        <?php if ($ark): ?>
        <li class="share">
            <a href="#psl-toolbox-share"></a>
        </li>
        <?php endif; ?>
        <?php if ($isMedia): ?>
            <li class="download">
                <a href="#psl-toolbox-download"></a>
            </li>
        <?php endif; ?>
    </ul>
    <?php if ($ark): ?>
    <div id="psl-toolbox-share">
        <label><?php echo $translate('Permalink'); ?></label>
        <a href="<?php echo $ark; ?>"><?php echo $ark; ?></a>
    </div>
    <?php endif; ?>
    <?php if ($isMedia): ?>
        <div id="psl-toolbox-download">
            <label><?php echo $translate('Original file:'); ?></label>
            <a href="<?php echo $resource->originalUrl(); ?>"><?php echo $resource->filename(); ?></a>
        </div>
    <?php endif; ?>
</div>
