<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 */

$translate = $this->plugin('translate');
$assetUrl = $this->plugin('assetUrl');

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
// The event "view.layout" is triggered before the preparation of the default
// links and scripts, so in all cases jQuery is loaded first and and custom css
// and js of the theme are loaded last. It resolves many issues with modules.
$this->trigger('view.layout');
$this->headLink()
    ->prependStylesheet($assetUrl('css/iconfonts.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/style.css'));
$this->headScript()
    ->prependFile($assetUrl('js/global.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->prependFile($assetUrl('vendor/jquery/jquery.min.js', 'Omeka'))
    ->appendFile($assetUrl('js/custom.js'), 'text/javascript', ['defer' => 'defer']);
$userBar = $this->userBar();

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <link rel="shortcut icon" href="<?php echo $assetUrl('img/favicon.ico'); ?>" type="image/x-icon" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>

        <header>
            <?php $headerContent = $this->themeSetting('header'); ?>
            <?php if ($headerContent): ?>
            <?php echo $headerContent; ?>
            <?php elseif ($this->themeSetting('logo')): ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
            <?php else: ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
            <?php endif; ?>

            <?php if ($this->themeSetting('display_main_menu')): ?>
            <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1,
                ]);
                ?>
            </nav>
            <?php endif; ?>

            <div class="user-links">
                <?php $identity = $this->identity(); ?>
                <?php if ($identity): ?>
                    <?php if ($this->getHelperPluginManager()->has('showBasketLink')) echo $this->showBasketLink(); ?>
                    <a href="<?php echo $this->escapeHtml($this->url('logout')); ?>"><?php echo $translate('Logout'); ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->escapeHtml($this->url('login', [], ['query' => ['redirect' => $this->url(null, [], true)]])); ?>"><?php echo $translate('Login'); ?></a>
                <?php endif; ?>
            </div>
        </header>

        <nav role="navigation" class="breadcrumbs">
            <a href="<?php echo $this->url('site', [], true); ?>"><?php echo $translate('Home'); ?></a>
            <?php $titleParts = $this->headTitle(); ?>
            <?php if (count($titleParts) > 1): ?>
                »
                <?php echo $titleParts[0]; ?>
            <?php endif; ?>
        </nav>

        <?php if (empty($isHomePage)): ?>
            <?php echo $this->SearchingForm(); ?>
        <?php else: ?>
        <div id="search-form-wrapper">
            <?php echo $this->SearchingForm(); ?>
        </div>
        <?php endif; ?>

        <main>
            <?php echo $this->messages(); ?>
            <?php echo $this->content; ?>
        </main>

        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>
